// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "src/prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // For Supabase: Use DIRECT_URL for migrations (direct connection on port 5432)
    // Get the correct DIRECT_URL from Supabase Dashboard > Settings > Database > Connection string > Direct connection
    // The direct connection URL should NOT use pooler.supabase.com hostname
    url: process.env.DIRECT_URL || process.env.DATABASE_URL || "",
  },
});